const mongoose = require('mongoose');

const bookingSchema = new mongoose.Schema(
  {
    bookingId: {
      type: String,
      unique: true,
      required: false, // Will be auto-generated by pre-save hook
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'User ID is required'],
    },
    address: {
      type: String,
      required: [true, 'Address is required'],
      trim: true,
    },
    wasteType: {
      type: String,
      required: [true, 'Waste type is required'],
      enum: ['Plastic', 'Paper', 'Metal', 'E-Waste', 'Glass'],
    },
    weight: {
      type: Number,
      required: [true, 'Weight is required'],
      min: [0.1, 'Weight must be greater than 0'],
    },
    preferredDate: {
      type: Date,
      required: [true, 'Preferred date is required'],
    },
    preferredTime: {
      type: String,
      required: [true, 'Preferred time is required'],
      enum: ['9:00 AM - 12:00 PM', '12:00 PM - 3:00 PM', '3:00 PM - 6:00 PM'],
    },
    status: {
      type: String,
      enum: ['Pending', 'Assigned', 'In Progress', 'Completed', 'Cancelled'],
      default: 'Pending',
    },
    ngoPartner: {
      type: String,
      trim: true,
    },
    agentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Agent',
      default: null,
    },
  },
  {
    timestamps: true,
  }
);

// Generate booking ID before saving
bookingSchema.pre('save', async function (next) {
  if (!this.bookingId) {
    try {
      const date = new Date();
      const year = date.getFullYear();
      const month = String(date.getMonth() + 1).padStart(2, '0');
      const day = String(date.getDate()).padStart(2, '0');
      
      // Count bookings created today
      const startOfDay = new Date(year, date.getMonth(), date.getDate());
      const endOfDay = new Date(year, date.getMonth(), date.getDate() + 1);
      
      const count = await mongoose.model('Booking').countDocuments({
        createdAt: {
          $gte: startOfDay,
          $lt: endOfDay,
        },
      });
      
      const sequence = String(count + 1).padStart(4, '0');
      this.bookingId = `BK-${year}${month}${day}-${sequence}`;
    } catch (error) {
      // Fallback if counting fails
      const timestamp = Date.now();
      this.bookingId = `BK-${timestamp}`;
    }
  }
  next();
});

// Index for faster queries
bookingSchema.index({ userId: 1, status: 1 });
bookingSchema.index({ agentId: 1, status: 1 });
bookingSchema.index({ status: 1, createdAt: -1 });

module.exports = mongoose.model('Booking', bookingSchema);

